### ISSUE TITLE
我咋报这个错

### ISSUE THREAD

**Issue by chenfd99** [1anc3r/Spine-Runtimes-Demo#3]
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load shared library 'gdx' for target: Linux, 32-bit

**Comment by chenfd99** [comment]
`10-15 11:38:42.331 19571-19571/me.lancer.spineruntimesdemo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: me.lancer.spineruntimesdemo, PID: 19571
    java.lang.ExceptionInInitializerError
        at java.lang.Class.newInstance(Native Method)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1068)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2386)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2545)
        at android.app.ActivityThread.access$1100(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1396)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:157)
        at android.app.ActivityThread.main(ActivityThread.java:5597)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:771)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:649)
     Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load shared library 'gdx' for target: Linux, 32-bit
        at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:117)
        at com.badlogic.gdx.utils.GdxNativesLoader.load(GdxNativesLoader.java:34)
        at com.badlogic.gdx.backends.android.AppActivity.<clinit>(AppActivity.java:419)
        at java.lang.Class.newInstance(Native Method) 
        at android.app.Instrumentation.newActivity(Instrumentation.java:1068) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2386) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2545) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:151) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1396) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:157) 
        at android.app.ActivityThread.main(ActivityThread.java:5597) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:771) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:649) 
     Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.lancer.spineruntimesdemo-1/base.apk"],nativeLibraryDirectories=[/data/app/me.lancer.spineruntimesdemo-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libgdx.so"
        at java.lang.Runtime.loadLibrary(Runtime.java:367)
        at java.lang.System.loadLibrary(System.java:1076)
        at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:113)`
